# Use the official Nginx image from Docker Hub
FROM nginx:alpine

# Remove the default Nginx configuration file
RUN rm /etc/nginx/conf.d/default.conf

# Copy our custom configuration file from the nginx directory
COPY nginx/nginx.conf /etc/nginx/conf.d/
